services:
 instance:
   image: 'ghcr.io/khemzal/alicia-server:breed'
   #build: 'C:/Users/x/alicia-server'
   restart: unless-stopped
   ports:
     - '10030-10033:10030-10033/tcp'
   ulimits:
     core: -1
   volumes:
      # If you bind `/alicia-server/config` to host filesystem, the default configuration
      # will be unavailable, and you have to manually to get it from the `/resources`
      # folder in the repository.
      #
      #- "./config:/var/lib/alicia-server/config"
      # 
      - "./logs:/var/lib/alicia-server/logs"
      - "./data:/var/lib/alicia-server/data"
      - "./dumps:/dumps"
